version: "3.8"

volumes:
  postgres_data:

services:
  bot:
    restart: always
    build: .
    volumes:
      - .:/app
    command: python run.py
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data